### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by mica79** [xfhomedream/flutter-fish-redux-study#1]
Error: 'Action' is imported from both 'package:fish_redux/src/redux/basic.dart' and 'package:flutter/src/widgets/actions.dart'.

**Comment by xfhomedream** [comment]
你好，你这导包了吗

**Comment by xfmaster** [comment]
> Error: 'Action' is imported from both 'package:fish_redux/src/redux/basic.dart' and 'package:flutter/src/widgets/actions.dart'.

你好，能把详细错误贴一下吗，谢谢

**Comment by mica79** [comment]
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp                                                                                   
Compiler message:                                                       
lib/home/main/reducer.dart:2:1: Error: 'Action' is imported from both 'package:fish_redux/src/redux/basic.dart' and 'package:flutter/src/widgets/actions.dart'.
import 'package:flutter/material.dart';                                 
^^^^^^

**Comment by mica79** [comment]
> > Error: 'Action' is imported from both 'package:fish_redux/src/redux/basic.dart' and 'package:flutter/src/widgets/actions.dart'.
> 
> 你好，能把详细错误贴一下吗，谢谢

Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp                                                                                   
Compiler message:                                                       
lib/home/main/reducer.dart:2:1: Error: 'Action' is imported from both 'package:fish_redux/src/redux/basic.dart' and 'package:flutter/src/widgets/actions.dart'.
import 'package:flutter/material.dart';                                 
^^^^^^                                         
麻烦你了,谢谢

**Comment by xfmaster** [comment]
你这里是不是一直是红色的？如果是的话点一下我标记的地方
![image](https://user-images.githubusercontent.com/14237960/61193415-d73bef00-a6ed-11e9-9c41-d8cfe206ffd7.png)

**Comment by mica79** [comment]
> 你这里是不是一直是红色的？如果是的话点一下我标记的地方
> ![image](https://user-images.githubusercontent.com/14237960/61193415-d73bef00-a6ed-11e9-9c41-d8cfe206ffd7.png)

不是的,这个我已经get了,跟我的flutter版本有关系吗?我现在是Flutter (Channel stable, v1.7.8+hotfix.3, on Linux, locale zh_CN.UTF-8)

**Comment by xfmaster** [comment]
方便把你报错的页面截个图吗

**Comment by mica79** [comment]
> 方便把你报错的页面截个图吗

这个问题解决了,是我的flutter版本的问题,现在的fish_redux在flutter1.7下面兼容性有问题,我现在用hide action把这个问题解决了,然后新的错误就来了
![image](https://user-images.githubusercontent.com/51775847/61194248-e5d8d500-a6f2-11e9-8e84-03e53543111e.png)

**Comment by xfmaster** [comment]
你的版本这么低，
![image](https://user-images.githubusercontent.com/14237960/61194399-bb3b4c00-a6f3-11e9-89cc-a08a61d5994f.png)我的版本是这个

**Comment by mica79** [comment]
> 你的版本这么低，
> ![image](https://user-images.githubusercontent.com/14237960/61194399-bb3b4c00-a6f3-11e9-89cc-a08a61d5994f.png)我的版本是这个

你这是可以运行的dart的版本范围,flutter现在stable下面最新的就是v1.7.8+hotfix.3,我这已经是最新的了

**Comment by mica79** [comment]
你的flutter doctor 看到的版本是多少啊

**Comment by xfmaster** [comment]
Flutter (Channel master, v1.6.1-pre.41

**Comment by mica79** [comment]
我这demo跑起来了,我去fish_redux那边看了下,有人问类似的问题,我这改了下就行了
![image](https://user-images.githubusercontent.com/51775847/61200275-77583f00-a713-11e9-98e6-d0bfda89e371.png)
![image](https://user-images.githubusercontent.com/51775847/61200296-863ef180-a713-11e9-8830-b5822c3f94c2.png)
谢谢

**Comment by xfmaster** [comment]
好的 ，但是这个问题我好想没碰到过额

**Comment by mica79** [comment]
> 好的 ，但是这个问题我好想没碰到过额

fish_redux升级之后的问题,0.2.3之后的asDependent被移除了,flutter1.7之后和fish_redux兼容性处问题,action冲突,参数也变化了一些,就是这样了

**Comment by xfmaster** [comment]
哦哦  是的 你改了fish_redux的版本咯
